export enum ClaimStatus {
  FILED = 'FILED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NEEDS_CORRECTION = 'NEEDS_CORRECTION',
}

