export enum LossEventType {
  DROUGHT = 'DROUGHT',
  FLOOD = 'FLOOD',
  PEST_INFESTATION = 'PEST_INFESTATION',
  DISEASE = 'DISEASE',
  HAIL = 'HAIL',
  FIRE = 'FIRE',
  STORM = 'STORM',
  HARVEST_END = 'HARVEST_END',
  OTHER = 'OTHER',
}

