export enum NotificationType {
  POLICY_OFFERED = 'POLICY_OFFERED',
  POLICY_ACCEPTED = 'POLICY_ACCEPTED',
  POLICY_REJECTED = 'POLICY_REJECTED',
  POLICY_FLAGGED = 'POLICY_FLAGGED',
  CLAIM_FILED = 'CLAIM_FILED',
  CLAIM_APPROVED = 'CLAIM_APPROVED',
  CLAIM_REJECTED = 'CLAIM_REJECTED',
  GENERAL = 'GENERAL',
}
